server.port=8443
server.servlet.context-path=/metadata

server.ssl.enabled=true
server.ssl.key-store=file:/opt/common/tls.jks
server.ssl.key-store-type=JKS
server.ssl.key-alias=tls
server.ssl.key-store-password=secret
server.ssl.key-password=secret

#Logging
logging.level.se.swedenconnect.metadata.aggregator.daemon.DaemonTask=INFO

#Configuration
metadata-aggregator.aggregate-config-dir=/opt/pyff
metadata-aggregator.recache-delay=600
metadata-aggregator.data-dir=/opt/aggregator
metadata-aggregator.cache-dir=/opt/aggregator/feed-cache
metadata-aggregator.key-source.type=jks
metadata-aggregator.key-source.localtion=${metadata-aggregator.data-dir}/metadata-aggregator.jks
metadata-aggregator.key-source.pass=secret
metadata-aggregator.key-source.alias=metadata
metadata-aggregator.key-source.cert-location=
metadata-aggregator.sign-algo=http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
metadata-aggregator.validity-hours=168
metadata-aggregator.cache-duration-minutes=120

#System
tomcat.ajp.port=8009
tomcat.ajp.remoteauthentication=false
tomcat.ajp.enabled=false
